"""empty message

Revision ID: 5257d81de595
Revises: aeb03a6667c2
Create Date: 2024-06-15 11:34:09.907602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5257d81de595'
down_revision = 'aeb03a6667c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('job_id', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('responsibilities', sa.String(length=1000), nullable=True),
    sa.Column('requirements', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('application')
    # ### end Alembic commands ###
